version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "826695974453"
    ECR_REPO_NAME: "streamlit-app-1"
    ECS_CLUSTER_NAME: "RagApp-fargate-cluster"
    ECS_SERVICE_NAME: "rag-app-service"
    ECS_CONTAINER_NAME: "my-container"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - REPOSITORY_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME"
      - IMAGE_TAG_FULL="$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - IMAGE_TAG="$(echo $IMAGE_TAG_FULL | cut -c 1-7)"
      - export REPOSITORY_URI
      - export IMAGE_TAG
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$REPOSITORY_URI"
      - echo "Ensuring ECR repository exists..."
      - aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" --region "$AWS_REGION" || aws ecr create-repository --repository-name "$ECR_REPO_NAME" --region "$AWS_REGION"
      - echo "Checking Dockerfile..."
      - test -f Dockerfile && echo "Dockerfile exists" || (echo "Dockerfile missing!" ; exit 1)

  build:
    commands:
      - echo "Listing files in build context..."
      - ls -al
      - echo "Building Docker image..."
      - docker build -t "$REPOSITORY_URI:$IMAGE_TAG" .
      - docker tag "$REPOSITORY_URI:$IMAGE_TAG" "$REPOSITORY_URI:latest"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push "$REPOSITORY_URI:$IMAGE_TAG"
      - docker push "$REPOSITORY_URI:latest"
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECS_CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yml
